from __future__ import annotations

from copy import deepcopy
import hashlib
import json
from typing import Any

from .public_contract import PublicContractProjector as BaseProjector, project_all
from .public_v2 import build_public_contract_v2, published_v2
from .public_v2 import compatibility_snapshot
from .v1_parity import close_v1_projection


_VOLATILE_PUBLIC_FIELDS = {"generated_at", "content_fingerprint", "contract_revision"}


def _stable_payload(payload: dict[str, Any]) -> dict[str, Any]:
    """Return semantic public truth without transport/revision metadata."""
    return {
        key: deepcopy(value)
        for key, value in payload.items()
        if key not in _VOLATILE_PUBLIC_FIELDS
    }


def _fingerprint(payload: dict[str, Any]) -> str:
    encoded = json.dumps(
        _stable_payload(payload),
        sort_keys=True,
        separators=(",", ":"),
        default=str,
    ).encode()
    return hashlib.sha256(encoded).hexdigest()


class PublicContractProjector(BaseProjector):
    """Single owner of canonical V2 + downstream V1 publication.

    Upstream runtime/store/metering/interaction callbacks can cascade during one
    physical event. request_recompute() collapses those notifications into one event
    loop transaction. A semantic fingerprint then suppresses publication entirely
    when the canonical V2 payload did not change.
    """

    def __init__(self, runtime, store, metering, interaction, manager) -> None:
        super().__init__(runtime, store, metering, interaction, manager)
        self._scheduled = None
        self._content_fingerprint: str | None = None
        self._contract_revision = 0
        self._recompute_request_count = 0
        self._projection_count = 0
        self._unchanged_skip_count = 0

    def get_parity_source(self) -> dict:
        """Return canonical compatibility truth from the same immutable V2 decision."""
        return deepcopy(getattr(self, "_parity_source", {}))

    def projection_diagnostics(self) -> dict[str, Any]:
        return {
            "recompute_request_count": self._recompute_request_count,
            "projection_count": self._projection_count,
            "unchanged_skip_count": self._unchanged_skip_count,
            "recompute_scheduled": self._scheduled is not None,
            "contract_revision": self._contract_revision,
            "content_fingerprint": self._content_fingerprint,
        }

    def request_recompute(self) -> None:
        self._recompute_request_count += 1
        if self._scheduled is not None:
            return
        # Collapse callbacks generated by one runtime transaction without adding
        # user-visible latency or another timer lifecycle.
        self._scheduled = self.runtime.hass.loop.call_soon(self._flush_recompute)

    def _flush_recompute(self) -> None:
        self._scheduled = None
        self.recompute()

    def recompute(self) -> None:
        snapshot = deepcopy(self.runtime.snapshot)
        model = self.manager.domain_model or {}
        battery = (model.get("concepts") or {}).get("battery_system") or {}
        snapshot["battery_reserve_write_supported"] = bool(battery.get("reserve_binding"))
        snapshot["settings"] = deepcopy(self.store.data.get("settings") or {})
        rows = self.interaction.command_rows()
        v2_contract = build_public_contract_v2(snapshot, self.store.data, rows, model)
        candidate_public = published_v2(v2_contract)
        fingerprint = _fingerprint(candidate_public)

        if self._content_fingerprint == fingerprint:
            self._unchanged_skip_count += 1
            return

        self._projection_count += 1
        self._contract_revision += 1
        self._content_fingerprint = fingerprint
        candidate_public["content_fingerprint"] = fingerprint
        candidate_public["contract_revision"] = self._contract_revision

        compatibility_source = compatibility_snapshot(v2_contract)
        projected = close_v1_projection(
            project_all(v2_contract, self.store.data, rows, self.manager),
            compatibility_source,
        )

        self._v2 = candidate_public
        self._parity_source = compatibility_source
        for object_id, payload in projected.items():
            if payload != self._cache.get(object_id):
                self._cache[object_id] = payload
                for callback in tuple(self._callbacks.get(object_id, [])):
                    callback()
        for callback in tuple(self._callbacks.get("__public_v2__", [])):
            callback()

    async def async_stop(self) -> None:
        if self._scheduled is not None:
            self._scheduled.cancel()
            self._scheduled = None
        await super().async_stop()
