from __future__ import annotations

import hashlib
import json
from time import perf_counter
from typing import Any

from .projection_base import PublicProjectionBase as BaseProjector
from .public_v2 import build_public_contract_v2


_VOLATILE_PUBLIC_FIELDS = {"generated_at", "content_fingerprint", "contract_revision"}


def _stable_payload(payload: dict[str, Any]) -> dict[str, Any]:
    """Return a read-only semantic view without recursively copying the payload."""
    return {
        key: value
        for key, value in payload.items()
        if key not in _VOLATILE_PUBLIC_FIELDS
    }


def _fingerprint(payload: dict[str, Any]) -> tuple[str, int]:
    encoded = json.dumps(
        _stable_payload(payload),
        sort_keys=True,
        separators=(",", ":"),
        default=str,
    ).encode()
    return hashlib.sha256(encoded).hexdigest(), len(encoded)


class PublicContractProjector(BaseProjector):
    """Single owner of canonical Energy Public V2 publication.

    Upstream runtime/store/metering/interaction callbacks can cascade during one
    physical event. request_recompute() collapses those notifications into one event
    loop transaction. A semantic fingerprint then suppresses publication entirely
    when the canonical V2 payload did not change.
    """

    def __init__(self, runtime, store, metering, interaction, manager) -> None:
        super().__init__(runtime, store, metering, interaction, manager)
        self._scheduled = None
        self._content_fingerprint: str | None = None
        self._contract_revision = 0
        self._recompute_request_count = 0
        self._projection_count = 0
        self._unchanged_skip_count = 0
        self._projection_total_ms = 0.0
        self._projection_max_ms = 0.0
        self._last_payload_bytes = 0


    def projection_diagnostics(self) -> dict[str, Any]:
        return {
            "recompute_request_count": self._recompute_request_count,
            "projection_count": self._projection_count,
            "unchanged_skip_count": self._unchanged_skip_count,
            "recompute_scheduled": self._scheduled is not None,
            "contract_revision": self._contract_revision,
            "content_fingerprint": self._content_fingerprint,
            "projection_total_ms": round(self._projection_total_ms, 3),
            "projection_average_ms": round(self._projection_total_ms / self._projection_count, 3) if self._projection_count else 0.0,
            "projection_max_ms": round(self._projection_max_ms, 3),
            "last_payload_bytes": self._last_payload_bytes,
        }

    def request_recompute(self) -> None:
        self._recompute_request_count += 1
        if self._scheduled is not None:
            return
        # Collapse callbacks generated by one runtime transaction without adding
        # user-visible latency or another timer lifecycle.
        self._scheduled = self.runtime.hass.loop.call_soon(self._flush_recompute)

    def _flush_recompute(self) -> None:
        self._scheduled = None
        self.recompute()

    def recompute(self) -> None:
        started = perf_counter()
        model = self.manager.domain_model or {}
        rows = self.interaction.command_rows()
        # build_public_contract_v2 owns its fresh output and copies only the mutable
        # inputs it needs. Avoid whole-snapshot copies before and after that build.
        candidate_public = build_public_contract_v2(
            self.runtime.snapshot,
            self.store.data,
            rows,
            model,
        )
        fingerprint, payload_bytes = _fingerprint(candidate_public)
        elapsed_ms = (perf_counter() - started) * 1000.0
        self._projection_total_ms += elapsed_ms
        self._projection_max_ms = max(self._projection_max_ms, elapsed_ms)
        self._last_payload_bytes = payload_bytes

        if self._content_fingerprint == fingerprint:
            self._unchanged_skip_count += 1
            return

        self._projection_count += 1
        self._contract_revision += 1
        self._content_fingerprint = fingerprint
        candidate_public["content_fingerprint"] = fingerprint
        candidate_public["contract_revision"] = self._contract_revision

        self._v2 = candidate_public
        for callback in tuple(self._callbacks.get("__public_v2__", [])):
            callback()

    async def async_stop(self) -> None:
        if self._scheduled is not None:
            self._scheduled.cancel()
            self._scheduled = None
        await super().async_stop()
